name: PKGBUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  package_path: ${{github.workspace}}/package
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Alpine package to ${{ env.package_path }} 
        uses: ./actions/
        with:
          output: ${{ env.package_path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gnirehtet.zip
          path: ${{ env.package_path }}/*.apk


