name: PKGBUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Alpine package 
        uses: ./actions/

      - name: Copy artifact
        run: |
          sudo mkdir ${{ github.workspace }}/release
          sudo cp /home/builder/packages/home/**/*.apk ${{ github.workspace }}/release

      - uses: actions/upload-artifact@v2
        with:
          name: gnirehtet.zip
          path: ${{ github.workspace }}/release/*.apk


