name: PKGBUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize Alpine package build env
        run: ls /github/home

